
import { db } from '../server/db.js';
import { completedProjectsTable } from '../shared/schema.js';

const historicalProjects = [
  {
    name: "Culligan Water Park Tashkent",
    type: "Water Treatment",
    status: "completed",
    location: "Tashkent",
    region: "Tashkent Region",
    country: "Uzbekistan",
    completion_date: "2003-04-11",
    capacity: 1000,
    total_investment: 2500000,
    dao_funding: 500000,
    estimated_irr: 15.5,
    project_duration: 24,
    beneficiaries: 365000,
    latitude: 41.2995,
    longitude: 69.2401,
    description: "Water purification equipment for Tashkent Water Park with 7 pools. High-tech solutions for drinking water quality standards with 3 powerful pumping stations ensuring continuous chemical and biological water purification.",
    impact_description: "10-hectare water park serving up to 1000 daily visitors with drinking water quality standards",
    environmental_impact: "Continuous chemical and biological water purification for 20+ years",
    technical_specifications: "3 pumping stations, 7 pools, drinking water standards",
    sdg_alignment: "Clean Water and Sanitation, Good Health and Well-being",
    technical_partners: "Culligan International",
    investment_stage: "operational"
  },
  {
    name: "Nemiroff Vodka Production Water Treatment",
    type: "Industrial Water Treatment",
    status: "completed", 
    location: "Nemirov",
    region: "Vinnytsa Region",
    country: "Ukraine",
    completion_date: "2003-11-21",
    capacity: 63,
    total_investment: 1800000,
    dao_funding: 400000,
    estimated_irr: 18.2,
    project_duration: 18,
    beneficiaries: 0,
    latitude: 49.0647,
    longitude: 28.8492,
    description: "High-tech water treatment equipment for alcoholic beverage production. Multi-stage processing: mechanical filtration, de-ironing, softening, reverse osmosis. Capacity 63 m³/hour for premium vodka production.",
    impact_description: "Premium vodka production with 140+ years heritage, distributed to 80 countries across 5 continents",
    environmental_impact: "Multi-stage water purification reducing industrial water consumption",
    technical_specifications: "63 m³/hour capacity, 4-stage processing: mechanical filtration, de-ironing, softening, reverse osmosis",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Nemiroff",
    investment_stage: "operational"
  },
  {
    name: "Kazakhstan Chemical Plant Water Treatment",
    type: "Chemical Industry Treatment",
    status: "completed",
    location: "Almaty",
    region: "Almaty Region", 
    country: "Kazakhstan",
    completion_date: "2004-07-02",
    capacity: 528,
    total_investment: 3200000,
    dao_funding: 640000,
    estimated_irr: 16.8,
    project_duration: 36,
    beneficiaries: 0,
    latitude: 43.2220,
    longitude: 76.8512,
    description: "Water treatment plant for chemical industry with filtering and demineralization functions. Capacity of 528 cubic meters per day for industrial chemical processes.",
    impact_description: "Industrial water treatment supporting chemical manufacturing operations",
    environmental_impact: "Filtering and demineralization reducing industrial water waste",
    technical_specifications: "528 m³/day capacity, filtering and demineralization systems",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Kazakhstan Chemical Plant",
    investment_stage: "operational"
  },
  {
    name: "World of Fitness Sports Complex",
    type: "Recreation Water Treatment",
    status: "completed",
    location: "Minsk",
    region: "Minsk Region",
    country: "Belarus", 
    completion_date: "2004-08-16",
    capacity: 200,
    total_investment: 1500000,
    dao_funding: 300000,
    estimated_irr: 14.5,
    project_duration: 12,
    beneficiaries: 6000,
    latitude: 53.9006,
    longitude: 27.5590,
    description: "Water treatment equipment for sports and health club covering 7,000 square meters. Serves 6,000 annual members with aquazones for children and adults.",
    impact_description: "7,000 m² sports complex serving 6,000 annual members with advanced aquatic facilities",
    environmental_impact: "Water treatment for recreational facilities promoting health and wellness",
    technical_specifications: "150+ exercise machines, aquazones, aerobics halls, yoga and pilates facilities",
    sdg_alignment: "Clean Water and Sanitation, Good Health and Well-being",
    technical_partners: "Culligan, World of Fitness",
    investment_stage: "operational"
  },
  {
    name: "Khortytsa Distillery Water System",
    type: "Beverage Production",
    status: "completed",
    location: "Zaporizhzhia",
    region: "Zaporizhzhia Oblast",
    country: "Ukraine",
    completion_date: "2004-09-07",
    capacity: 150,
    total_investment: 2200000,
    dao_funding: 440000,
    estimated_irr: 19.3,
    project_duration: 24,
    beneficiaries: 0,
    latitude: 47.8388,
    longitude: 35.1396,
    description: "Advanced water treatment for premium vodka production including reverse osmosis, silver and platinum filtration, carbon filters and water structuring unit. Top 3 global vodka brand.",
    impact_description: "Premium vodka production for top 3 global brand with advanced filtration technology",
    environmental_impact: "Precious metal filtration system ensuring highest quality water treatment",
    technical_specifications: "Reverse osmosis, silver and platinum filtration, carbon filters, water structuring unit",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Khortytsa Distillery",
    investment_stage: "operational"
  },
  {
    name: "Boryspil International Airport Water Supply",
    type: "Airport Infrastructure",
    status: "completed",
    location: "Boryspil",
    region: "Kyiv Oblast",
    country: "Ukraine",
    completion_date: "2004-11-23",
    capacity: 1500,
    total_investment: 4500000,
    dao_funding: 900000,
    estimated_irr: 13.2,
    project_duration: 18,
    beneficiaries: 8000000,
    latitude: 50.3450,
    longitude: 30.8947,
    description: "Drinking water supply system for Ukraine's largest international airport. Capacity of 1,500 cubic meters per day serving 8+ million annual passengers with mechanical filtration, degreasing and disinfection.",
    impact_description: "International airport water supply serving 8+ million annual passengers",
    environmental_impact: "Large-scale water treatment with mechanical filtration and disinfection",
    technical_specifications: "1,500 m³/day capacity, mechanical filtration, degreasing, disinfection",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Boryspil Airport",
    investment_stage: "operational"
  },
  {
    name: "Chernogolovka Beverages Water Treatment",
    type: "Soft Drink Production",
    status: "completed",
    location: "Chernogolovka",
    region: "Moscow Oblast",
    country: "Russia",
    completion_date: "2005-04-14",
    capacity: 300,
    total_investment: 2800000,
    dao_funding: 560000,
    estimated_irr: 17.4,
    project_duration: 20,
    beneficiaries: 0,
    latitude: 56.0167,
    longitude: 38.3833,
    description: "Multi-level water purification system for traditional Russian lemonades production. Uses artesian water from wells up to 170m deep, controlled by 20+ quality indicators for natural beverages without artificial additives.",
    impact_description: "Traditional Russian lemonade production using natural ingredients and artesian water",
    environmental_impact: "Artesian water utilization with 20+ quality control parameters",
    technical_specifications: "Wells up to 170m deep, 20+ quality indicators, 9 beverage types, no artificial additives",
    sdg_alignment: "Clean Water and Sanitation, Good Health and Well-being",
    technical_partners: "Culligan, Drinks from Chernogolovka",
    investment_stage: "operational"
  },
  {
    name: "Gazprom Headquarters Water System", 
    type: "Corporate Complex",
    status: "completed",
    location: "Moscow",
    region: "Moscow",
    country: "Russia",
    completion_date: "2005-06-02",
    capacity: 800,
    total_investment: 5200000,
    dao_funding: 1040000,
    estimated_irr: 12.8,
    project_duration: 24,
    beneficiaries: 15000,
    latitude: 55.7558,
    longitude: 37.6176,
    description: "Comprehensive water treatment system for Gazprom headquarters complex including main building, polyclinic, sports complex with pool, restaurant, hotel and concert facilities.",
    impact_description: "Corporate headquarters complex serving world's largest gas company",
    environmental_impact: "Integrated water treatment for multi-building corporate complex",
    technical_specifications: "Main building, polyclinic, sports complex, pool, restaurant, hotel, concert hall",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Gazprom",
    investment_stage: "operational"
  },
  {
    name: "ALROSA Diamond Mining Water Treatment",
    type: "Mining Industry",
    status: "completed",
    location: "Mirny",
    region: "Sakha Republic",
    country: "Russia",
    completion_date: "2005-10-07",
    capacity: 800,
    total_investment: 6800000,
    dao_funding: 1360000,
    estimated_irr: 20.1,
    project_duration: 30,
    beneficiaries: 8000,
    latitude: 62.5354,
    longitude: 113.9669,
    description: "Water filtration systems for world's largest diamond producer. Capacity of 800 cubic meters per day serving mining operations that extract 25% of global diamond production.",
    impact_description: "Mining operations for world's largest diamond producer extracting 25% of global production",
    environmental_impact: "Industrial water treatment for sustainable diamond mining operations",
    technical_specifications: "800 m³/day capacity, mining industry specifications, 18-20 year reserve support",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, ALROSA",
    investment_stage: "operational"
  },
  {
    name: "Ashgabat Water Treatment Plant",
    type: "Municipal Water Supply",
    status: "completed",
    location: "Ashgabat",
    region: "Ahal Region",
    country: "Turkmenistan",
    completion_date: "2006-08-09",
    capacity: 320000,
    total_investment: 200000000,
    dao_funding: 40000000,
    estimated_irr: 11.5,
    project_duration: 96,
    beneficiaries: 1200000,
    latitude: 37.9601,
    longitude: 58.3261,
    description: "Massive water treatment plant opened by President of Turkmenistan. Capacity of 320,000 cubic meters per day. Part of comprehensive water infrastructure reconstruction including desalination plants and pumping stations.",
    impact_description: "National water infrastructure project serving 1.2 million people in capital city",
    environmental_impact: "Massive water treatment capacity supporting national water security",
    technical_specifications: "320,000 m³/day capacity, desalination plants, pumping stations, waterworks reconstruction",
    sdg_alignment: "Clean Water and Sanitation, Sustainable Cities and Communities",
    technical_partners: "Culligan, Government of Turkmenistan",
    investment_stage: "operational"
  },
  {
    name: "Mercury Mineral Water Plant",
    type: "Mineral Water Production",
    status: "completed",
    location: "Cherkessk",
    region: "Karachay-Cherkessia",
    country: "Russia",
    completion_date: "2006-09-05",
    capacity: 400,
    total_investment: 8500000,
    dao_funding: 1700000,
    estimated_irr: 16.9,
    project_duration: 36,
    beneficiaries: 0,
    latitude: 44.2232,
    longitude: 42.0577,
    description: "Artesian water filtration for mineral water bottling plant. Production capacity of 370+ million bottles annually across 3,600 square meters including production workshop, logistics complex and rail infrastructure.",
    impact_description: "Major mineral water production facility with 370+ million annual bottle capacity",
    environmental_impact: "Artesian water utilization for mineral water production in North Caucasus",
    technical_specifications: "370+ million bottles/year, 3,600 m² facility, production workshop, logistics, rail access",
    sdg_alignment: "Clean Water and Sanitation, Industry Innovation and Infrastructure",
    technical_partners: "Culligan, Mercury Water Company",
    investment_stage: "operational"
  },
  {
    name: "Belovezhsky Cheeses Water Treatment",
    type: "Dairy Production",
    status: "completed",
    location: "Vysokaye",
    region: "Brest Region",
    country: "Belarus",
    completion_date: "2007-12-21",
    capacity: 200,
    total_investment: 1200000,
    dao_funding: 240000,
    estimated_irr: 15.8,
    project_duration: 18,
    beneficiaries: 50000,
    latitude: 52.3167,
    longitude: 23.3667,
    description: "Water treatment equipment for premium cheese production including Mozzarella and Belovezhsky Parmesan. Serves modernized facility producing 20+ types of semi-hard cheeses since 1938.",
    impact_description: "Premium cheese production facility with 20+ varieties serving regional market",
    environmental_impact: "Sustainable water treatment for dairy production supporting local agriculture",
    technical_specifications: "20+ cheese types, Mozzarella, Belovezhsky Parmesan, Golden Cheese, modernized facility",
    sdg_alignment: "Clean Water and Sanitation, Responsible Consumption and Production",
    technical_partners: "Culligan, Belovezhsky Cheeses JSC",
    investment_stage: "operational"
  }
];

async function seedHistoricalProjects() {
  try {
    console.log('🌊 Добавление исторических водных проектов Culligan...');
    
    for (const project of historicalProjects) {
      console.log(`- Добавляю проект: ${project.name}`);
      await db.insert(completedProjectsTable).values(project);
    }
    
    console.log('✅ Успешно добавлено', historicalProjects.length, 'исторических проектов');
    console.log('📊 Проекты охватывают период 2003-2007 гг.');
    console.log('🌍 География: Узбекистан, Украина, Казахстан, Беларусь, Россия, Туркменистан');
    
  } catch (error) {
    console.error('❌ Ошибка при добавлении исторических проектов:', error);
  }
}

// Запускаем если файл вызван напрямую
if (import.meta.url === `file://${process.argv[1]}`) {
  seedHistoricalProjects();
}

export { seedHistoricalProjects };
